job_board/urls.py
from django.conf.urls.defaults import *
from django.contrib.sitemaps import FlatPageSitemap, GenericSitemap

from job_board.models import Job
from job_board.feeds import JobFeed
from job_board.forms import JobForm
from job_board.views import JobFormPreview, job_list, job_detail, job_search

feeds = {
    'jobs': JobFeed,
}

info_dict = {
    'queryset': Job.objects.filter(),
    'date_field': 'posted'
}

sitemaps = {
    'flatpages': FlatPageSitemap,
    'jobs': GenericSitemap(info_dict, priority=0.6),
}

urlpatterns = patterns('',
    url(r'^feed/(?P<url>.*)/$',
        'django.contrib.syndication.views.feed',
        {'feed_dict': feeds},
        name='job-feeds'),

    url(r'^sitemap.xml$',
        'django.contrib.sitemaps.views.sitemap',
        {'sitemaps': sitemaps},
        name='job-sitemap'),
    
    url(r'^new/$',
        JobFormPreview(JobForm),
        name='job-form'),

    url(r'^(?P<object_id>\d+)/(?P<slug>[\w-]+)/$',
        job_detail,
        name='job-detail'),

    url(r'^wmd/', include('wmd.urls')),

    url(r'^search/$',
        job_search,
        name='job-search'),

    url(r'^$',
        job_list,
        name='job-list'), # This must be last after everything else has been evaluated
)

job_board/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.sitemaps import ping_google
from django.utils.translation import ugettext_lazy as _

from job_board.manager import JobManager
from job_board.signals import view_job
from wmd import models as wmd_models

TYPE = (
        ('P', _('Permanent')),
        ('C', _('Contract')),
        ('I', _('Internship')),
    )

class JobCategory(models.Model):
    name            = models.CharField(max_length=50)
    description     = models.TextField(null=True, blank=True)
    slug            = models.SlugField(max_length=50)

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return "/category/%s/" % ( self.slug )

    class Meta:
        verbose_name_plural = _('categories')
        ordering = ['name']

class Checklist(models.Model):
    question        = models.CharField(max_length=100)

class Job(models.Model):
    title           = models.CharField(max_length=50, verbose_name=_('job title'),
                      help_text=_('job title'))
    slug            = models.SlugField(max_length=50)
    description     = wmd_models.MarkDownField()
    posted          = models.DateTimeField(auto_now_add=True)
    location        = models.CharField(max_length=128, null=True, blank=True, help_text=_('job location'))
    onsite_required = models.BooleanField(default=True)
    job_type        = models.CharField(max_length=1, choices=TYPE)
    category        = models.ForeignKey(JobCategory, verbose_name=_('job category'))
    to_apply        = models.CharField(max_length=128, verbose_name=_('how to apply'),
                      help_text=_('"Send your resume to John Doe (john.doe@company.com)"'))
    website         = models.URLField(verify_exists=False, null=True, blank=True,
                      help_text=_('"www.company.com"'))
    company_name    = models.CharField(max_length=128)
    viewed          = models.IntegerField(editable=False, default=1)
    checklist       = models.ManyToManyField(Checklist, through='JobChecklist')

    objects = JobManager()

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return "/%d/%s/" % ( self.id, self.slug )

    def save(self):
        self.slug = slugify(self.title)
        super(Job, self).save()
        
        try:
             ping_google()
        except Exception:
             # Bare 'except' because we could get a variety
             # of HTTP-related exceptions.
             pass

    def on_job_view(sender, **kwargs):
        job = kwargs['job']
        job.viewed = job.viewed + 1
        job.save()

    view_job.connect(on_job_view)

    class Meta:
        ordering = ['-posted']
        get_latest_by = 'posted'

class JobChecklist(models.Model):
    checklist       = models.ForeignKey(Checklist)
    job             = models.ForeignKey(Job)
    answer          = models.BooleanField()

    class Meta:
        db_table = 'job_board_job_checklist'

job_board/forms.py
from django import forms
from django.forms import ModelForm
from django.utils.translation import ugettext_lazy as _

from job_board.models import *
from wmd.widgets import MarkDownInput

class JobForm(ModelForm):
    description = forms.CharField(widget=MarkDownInput(attrs={'cols': 90, 'rows': 15}))
    onsite_required = forms.BooleanField(initial=True, required=False)
    honeypot    = forms.CharField(required=False,
                                label=_('If you enter anything in this field '\
                                        'your comment will be treated as spam'))

    def clean_honeypot(self):
        """Check that nothing's been entered into the honeypot."""
        value = self.cleaned_data["honeypot"]
        if value:
            raise forms.ValidationError(self.fields["honeypot"].label)
        return value
    
    class Meta:
        model = Job
        fields = ('title', 'category', 'job_type', 'description', 
                  'company_name', 'onsite_required', 'location',
                  'website', 'to_apply')

job_board/views.py
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.template.loader import select_template
from django.contrib.formtools.preview import FormPreview
from django.views.generic import list_detail

from commons.search import get_query

from job_board.models import *
from job_board.forms import *
from job_board.signals import view_job

queryset = Job.objects.filter_date()

template_object_name = 'job'

paginate_by = 10

job_list_template = (
    "job_board/list.html",
    "job_board/job_list.html",
)

def job_list(request):
    template = select_template(job_list_template) # returns Template object
    template_name = template.name
    
    return list_detail.object_list(request, queryset,
                                    paginate_by = paginate_by,
                                    template_name = template_name,
                                    template_object_name = template_object_name)
    
def job_search(request):
    query_string = ''

    if ('q' in request.GET) and request.GET['q'].strip():
        query_string = request.GET['q']

        query = get_query(query_string, ['title', 'location', 'description', 'company_name', 'website'])

        queryset = Job.objects.filter_date().filter(query).order_by('-posted')

    template = select_template(job_list_template) # returns Template object
    template_name = template.name

    return list_detail.object_list(request, queryset,
                                    paginate_by = paginate_by,
                                    template_name = template_name,
                                    template_object_name = template_object_name)


def job_detail(request, slug=None, object_id=None):
    job_detail_template = (
        "job_board/view.html",
        "job_board/detail.html",
        "job_board/job_detail.html",
    )
    
    template = select_template(job_detail_template)
    template_name = template.name

    job = Job.objects.get(pk=object_id)
    view_job.send(sender=job_detail, job=job)

    return list_detail.object_detail(request, queryset,
                                     object_id = object_id,
                                     slug = slug,
                                     template_name = template_name,
                                     template_object_name = template_object_name)     

class JobFormPreview(FormPreview):
    preview_template = 'job_board/preview.html'
    form_template = 'job_board/form.html'
        
    def done(self, request, cleaned_data):
        form = JobForm(request.POST)
        job = form.save()

        message = """Your job posting has been saved successfully. Thank you very much.
        """

        request.notifications.create(message, 'success')

        params = {'slug': job.slug, 'object_id': job.id}
        return HttpResponseRedirect(reverse('job-detail', kwargs=params))

job_board/templates/job_board/base_form.html
{% load i18n %}

<form id="entry-form" action="." method="POST">
    {% for field in form %}

        {% if field.errors %}
            <ol class="errorlist">
            {% for error in field.errors %}
                <li><strong>{{ error|escape }}</strong></li>
            {% endfor %}
            </ol>
        {% endif %}
        <p {% ifequal field.name "honeypot" %} style="display:none;"{% endifequal %}>
        {% ifequal field.name "onsite_required" %}
        {{ field }} <label class="inline">{{ field.label }}</label>
        {% else %}
            {{ field.label_tag }} {{ field }}
        {% endifequal %}
            <span>{{ field.help_text }}</span>
        </p>
    {% endfor %}

    <input type="submit" value="{% trans 'Preview' %}" />
    <input type="hidden" name="{{ stage_field }}" value="1" />
</form>

job_board/templates/job_board/feed.html
{% load markup %}
{% load i18n %}

<h2 class="title">{{ obj.title }} <span>{% trans 'at' %}</span>&nbsp;{{ obj.company_name }}</h2>
{% if obj.website %}<div><strong>{% trans 'Website' %}:</strong>&nbsp;{{ obj.website|urlize }}</div>{% endif %}
<div><strong>{% trans 'Type' %}:</strong>&nbsp;{{ obj.get_job_type_display }}</div>
<div><strong>{% trans 'Location' %}:</strong>&nbsp;{{ obj.location }}&nbsp;
    {% if obj.onsite_required %}({% trans 'Required onsite' %}){% endif %}</div>

<strong>{% trans 'Description' %}:</strong>
<div class="desc">
{{ obj.description|markdown }}
</div>

<div><strong>{% trans 'To apply' %}:</strong> {{ obj.to_apply|urlize }}</div>

job_board/templates/job_board/form.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
<div id="content">
    <div style="margin-bottom:1em">&laquo; <a href="{% url job-list %}">{% trans 'Back' %}</a></div>
    
    {% include 'job_board/base_form.html' %}

    <div style="margin-top:1em">&laquo; <a href="{% url job-list %}">{% trans 'Back' %}</a></div>
</div>
{% endblock %}

job_board/templates/job_board/list.html
{% extends 'base.html' %}

{% load i18n %}

{% block content %}
<div id="content">
    <div style="float:left">
        <form method="get" action="{% url job-search %}">
            <input type="text" name="q" size="30"/>
            <input type="submit" value="Search"/>
        </form>
    </div>
    
    <div id="form-link-wrapper">
        <span id="form-link">
            <a href="{% url job-form %}">{% trans 'Post your jobs for free here!' %}</a>
        </span>
        <br/>
        {% trans 'Your job posting will be displayed for 30 days.' %}
    </div>
    <div style="clear:both"></div>    

    <div id="job-list">
    {% for job in job_list %}
        <div class="block {% cycle 'odd' 'even' %}">
            <strong>
                {% if job.onsite_required %}
                    {{ job.location }}
                {% else %}
                    {% trans 'Telecommute' %}
                {% endif %}
            </strong>: <a href='{{ job.get_absolute_url }}'>{{ job.title }}</a>
            <span class="small">{% trans 'at' %}</span>
            
            {% if job.website %} 
            <a href="{{ job.website }}">{{ job.company_name }}</a>
            {% else %}
            {{ job.company_name }}
            {% endif %}

            <span class="small"><em>{% trans 'viewed' %}</em> job.viewed {% trans 'times' %} <em>{% trans 'since' %}</em>
                {{ job.posted|timesince }} <em>ago</em></span>
        </div>
    {% endfor %}
    </div>

    <div id="feeds-link-wrapper">
        <span id="feeds-link">
            <a href="{% url job-feeds 'jobs' %}" >
                {% trans 'Stay updated by subscribing to our job feeds' %}
            </a>
        </span>
    </div>
</div>
{% endblock %}

job_board/templates/job_board/preview.html
{% extends 'base.html' %}

{% load markup %}
{% load i18n %}

{% block content %}
<div id="content">
    
    <h2 class="title">{{ form.title.data }} <span>{% trans 'at' %}</span> {{ form.company_name.data }}</h2>
    {% if form.website %}<div><strong>{% trans 'Website' %}:</strong> {{ form.website.data|urlize }}</div>{% endif %}
    <div><strong>{% trans 'Category' %}:</strong> {{ form.cleaned_data.category }}</div>
    <div><strong>{% trans 'Type' %}:</strong>
        {% ifequal form.cleaned_data.job_type 'P' %}{% trans 'Permanent' %}{% endifequal %}
        {% ifequal form.cleaned_data.job_type 'C' %}{% trans 'Contract' %}{% endifequal %}
        {% ifequal form.cleaned_data.job_type 'I' %}{% trans 'Internship' %}{% endifequal %}
    </div>

    <div><strong>{% trans 'Location' %}:</strong>
        {% if job.onsite_required %}
            {{ job.location }}
        {% else %}
            {% trans 'Telecommute' %}
        {% endif %}&nbsp;
    </div>

    <div class="desc">
    {% autoescape on %}{{ form.description.data|markdown }}{% endautoescape %}
    </div>

    <div><strong>{% trans 'To apply' %}:</strong> {{ form.to_apply.data|urlize }}</div>

    <form action="." method="post">
        {% for field in form %}
        {{ field.as_hidden }}
        {% endfor %}
        <input type="hidden" name="{{ stage_field }}" value="2" />
        <input type="hidden" name="{{ hash_field }}" value="{{ hash_value }}" />
        <p><input type="submit" value="Submit" /></p>
    </form>

    <h2 class="title" style="margin-top:1em">{% trans 'Edit' %}</h2>
    {% include 'job_board/base_form.html' %}
    
</div>
{% endblock %}

job_board/templates/job_board/view.html
{% extends 'base.html' %}

{% load markup %}
{% load i18n %}

{% block content %}
<div id="content"> 
    <div style="margin-bottom:1em">&laquo; <a href="{% url job-list %}">{% trans 'Back' %}</a></div>

    {% if notifications %}
    <ul id="notifications">
        {% for notification in notifications %}<li class="{{ notification.type }}">{{ notification.content }}</li>
        {% endfor %}
    </ul>
    {% endif %}
    
    <h2 class="title">{{ job.title }}<span>&nbsp;{% trans 'at' %}</span>&nbsp;{{ job.company_name }}</h2>
    {% if job.website %}<div><strong>{% trans 'Website' %}:</strong> {{ job.website|urlize }}</div>{% endif %}
    <div><strong>{% trans 'Category' %}:</strong>&nbsp;{{ job.category }}</div>
    <div><strong>{% trans 'Type' %}:</strong>&nbsp;{{ job.get_job_type_display }}</div>
    <div><strong>{% trans 'Location' %}:</strong>
        {% if job.onsite_required %}
            {{ job.location }}
        {% else %}
            {% trans 'Telecommute' %}
        {% endif %}&nbsp;
    </div>

    <div class="desc">
    {% autoescape on %}{{ job.description|markdown }}{% endautoescape %}
    </div>

    <div><strong>{% trans 'To apply' %}:</strong> {{ job.to_apply|urlize }}</div>

    <div style="margin-top:1em">&laquo; <a href="{% url job-list %}">{% trans 'Back' %}</a></div>
</div>
{% endblock %}